language: python

env:
  global:
    - CONDA_CHANNELS='astropy-ci-extras astropy'
    - CONDA_DEPENDENCIES="astropy scipy matplotlib jupyter pandas"
    - PIP_DEPENDENCIES="git+https://github.com/spacetelescope/jwst.git"
    - MC_URL=https://repo.continuum.io/miniconda
    - CRDS_SERVER_URL='https://jwst-crds.stsci.edu'
    - CRDS_PATH='/tmp/crds_cache'
    - PYTHON_VERSION="3.5"

matrix:
  # Don't wait for allowed failures
  fast_finish: true
  include:
    # Run tests
    - env: TEST_COMMAND='python setup.py test'
           PIP_DEPENDENCIES='.[test]'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
#     - pip install git+https://github.com/eteq/nbpages.git#egg=nbpages

script: $TEST_COMMAND
